# Generated by Django 5.2.7 on 2025-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_muscle', models.CharField(max_length=50)),
                ('muscles_secondary', models.TextField(blank=True)),
                ('equipment', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('is_compound', models.BooleanField(default=False)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.CharField(blank=True, max_length=50)),
                ('weight', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('rest_time', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='exercises/')),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
